### PR TITLE
AccordionItem closes when another is opened, add free boolean for opening multiple

### LINKED ISSUE #994: Collapse -> Accordion not working
Collapse works, but not accordion.
"Note that only one collapse in an accordion group can be open at a time." - that is not working 
it works in "bootstrap vue"

OS: [e.g. Windows 10]
Package Version: [0.7.3]
Npm Version: [npm@9.2.0]

### PR DESCRIPTION
**Pull request by xvaara**
As the title says.
fixes #994 
Adds v-modal to BAccordion that is the id of the open accordion. 
Add free booleanish to open multiple
Integrate more with BCollapse

### CODE REVIEW

File: packages/bootstrap-vue-next/src/components/BCollapse.vue [hunk 1]
```diff
@@ -15,14 +15,13 @@
...
-import {computed, nextTick, onMounted, ref, toRef, watchEffect} from 'vue'
+import {computed, nextTick, onMounted, ref, toRef, watch, watchEffect} from 'vue'
 import {useBooleanish, useId} from '../composables'
 import {useEventListener, useVModel} from '@vueuse/core'
 import type {Booleanish} from '../types'
 import {BvTriggerableEvent} from '../utils'
 
-interface BCollapseProps {
-  accordion?: string
+export interface BCollapseProps {
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BCollapse.vue:24]: I don't think you're allowed to export from script setup

Comment (xvaara) [reply packages/bootstrap-vue-next/src/components/BCollapse.vue:24]: I think because it's only typescript functionality it's allowed. It is exported before the vue compiler munches over the setup part. Not sure, but some random stackoverflow post said you could do this and it works... so 😅🤷 up to you.

Comment (VividLemon) [reply packages/bootstrap-vue-next/src/components/BCollapse.vue:24]: Okay, so this is possible. I thought it would first error on you because there is an eslint rule to disable named exports in script setup.

However this is a type and will not suffer from the limitation presented by (exporting a variable from a setup function that is inside of a export default object), just doesn't make sense.

However, there is still an issue with the usage of this, I will describe in a different comment

Comment (xvaara) [reply packages/bootstrap-vue-next/src/components/BCollapse.vue:24]: it's used in vue docs on script setup: https://vuejs.org/api/sfc-script-setup.html#default-props-values-when-using-type-declaration

File: packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue [hunk 2]
```diff
@@ -29,41 +28,57 @@
...
-import BCollapse from '../BCollapse.vue'
+import {default as BCollapse, type BCollapseEmits, type BCollapseProps} from '../BCollapse.vue'
+// import  from '../BCollapse.vue'
 import {accordionInjectionKey} from '../../utils'
-import {useBooleanish, useId} from '../../composables'
+import {useId} from '../../composables'
 import type {Booleanish} from '../../types'
 
-interface BAccordionItemProps {
+interface BAccordionItemProps extends BCollapseProps {
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue:45]: This is **impossible** syntax. Extending prop types will break Vue as it's currently not supported by the Vue compiler. Your best bet is to just duplicate the props and leave a note. Alternatively, you could revert the component to <script> and use real objects, as shown in BLink & components that depend on its props. However, this is not the best option, I'd prefer to just duplicate the props and use a note.

File: packages/bootstrap-vue-next/src/components/BCollapse.vue (hunk 1 above)
Comment (VividLemon) [reply packages/bootstrap-vue-next/src/components/BCollapse.vue:24]: > it's used in vue docs on script setup: https://vuejs.org/api/sfc-script-setup.html#default-props-values-when-using-type-declaration

The problem is not with exporting a type, the problem is with extending a prop type, as the Vue compiler cannot crawl types:
https://vuejs.org/guide/typescript/composition-api.html#syntax-limitations 
> This is because Vue components are compiled in isolation and the compiler currently does not crawl imported files in order to analyze the source type. This limitation could be removed in a future release.

File: packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue (hunk 2 above)
Comment (xvaara) [reply packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue:45]: it works, You can't export an extended interface, that's what vue compiler doesn't support.
here's the bug for that: https://github.com/vuejs/core/issues/7794

Comment (xvaara) [reply packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue:45]: ah now I get what you mean:
https://sfc.vuejs.org/#eNqVkd1ugzAMhV/Fyk1biZ97RpH28wB7gNwwaihVcSLbtJ0Q774AnVZ106bdRIljfzrneDCP3ienHk1mcqm49QqC2ns4ltRsrVGxprDUdt6xgr57hAFe2Xl5KgVhhJpdB6skfXbdDFqFZlLkuqxwaQS8KNJObsYGqJ3LQJRbagIELFWORMHPA1s4t7p/wbrsjyrrHdYt4Tydz2ex3kQwjJsHS3m6qC5MZBaRcVf65CCOgqXBUmBfP4KTDObKVAtSp7c1e1UvWZpKXU36D5I4btJwS7gnbTtMULr4jd1ZkAPYmuiGkYbiCTnm4BAZ+TfmXes37oQdLY3Bymeaf6wFL/Na7gK/Rjwt6yvj/yU8IX5MefwAg0rGqA==

Comment (xvaara) [reply packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue:45]: we don't need them (BCollapseProps) in vue side anyway. But it works on the editor, I get the code completion from BCollapseProps for BAccordionItem. Every prop that BAccordionItem uses is defined in that interface. Everything else is forwarded to BCollapse.

Comment (xvaara) [reply packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue]: So if vue implements a fix for the extends interface, It'll break this. So maybe better to do this the hard way. 😅

File: packages/bootstrap-vue-next/src/components/BAccordion/BAccordion.vue [hunk 3]
```diff
@@ -9,18 +9,23 @@ import type {Booleanish} from '../../types'
...
   id?: string
+  modelValue?: string
 }
 
 const props = withDefaults(defineProps<BAccordionProps>(), {
   flush: false,
   free: false,
 })
 
+const emit = defineEmits<(e: 'update:modelValue', value: string) => void>()
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BAccordion/BAccordion.vue:26]:
```suggestion
const emit = defineEmits<(e: 'update:modelValue', value: string) => void>()

```

File: packages/bootstrap-vue-next/src/components/BCollapse.vue [hunk 4]
```diff
@@ -180,7 +178,7 @@ if (visibleBoolean.value) {
   show.value = true
 }
 
-watchEffect(() => {
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BCollapse.vue:183]: Why did you remove this watchEffect

Comment (xvaara) [reply packages/bootstrap-vue-next/src/components/BCollapse.vue:183]: it was launching open() twice, don't know why. As general I've had so much problems with watchEffect in this project that it's the first thing I remove and usually it works.

Comment (VividLemon) [reply packages/bootstrap-vue-next/src/components/BCollapse.vue:183]: > it was launching open() or close() everytime mounted, don't know why. As general I've had so much problems with watchEffect in this project that it's the first thing I remove and usually it works.

You should try to take a look at https://vuejs.org/api/reactivity-core.html#watcheffect and their 
```ts
interface WatchEffectOptions {
  flush?: 'pre' | 'post' | 'sync' // default: 'pre'
  onTrack?: (event: DebuggerEvent) => void
  onTrigger?: (event: DebuggerEvent) => void
}
```
I'd try messing around with the flush value. It's kind of a longshot, but who knows, maybe it will magically fix the issue?

File: packages/bootstrap-vue-next/src/components/BCollapse.vue [hunk 5]
```diff
@@ -180,7 +178,7 @@ if (visibleBoolean.value) {
...
+watch(visibleBoolean, () => {
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BCollapse.vue:181]: You will likely want 
```ts
watch(visibleBoolean, (newValue) => {
  newValue ? ...
}
```

File: packages/bootstrap-vue-next/src/components/BCollapse.vue (hunk 4 above)
Comment (xvaara) [reply packages/bootstrap-vue-next/src/components/BCollapse.vue:183]: It doesn't. watchEffect is run always, not only on change. It also watches all the reactive variables in the functions.

File: packages/bootstrap-vue-next/src/components/BAccordion/BAccordion.vue [hunk 6]
```diff
@@ -30,9 +36,8 @@ const computedClasses = computed(() => ({
   'accordion-flush': flushBoolean.value,
 }))
 
-if (!freeBoolean.value) {
-  provide(accordionInjectionKey, {
-    id: computedId,
-  })
-}
+provide(accordionInjectionKey, {
+  openItem: modelValue,
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BAccordion/BAccordion.vue:40]: I'd suggest wrapping this in readonly

File: packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue [hunk 7]
```diff
@@ -29,41 +34,77 @@
   </div>
 </template>
 
+<script lang="ts">
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue:37]: Move this block to the bottom of the file

File: packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue [hunk 8]
```diff
@@ -29,41 +34,77 @@
...
 <script setup lang="ts">
-import {inject, onMounted, toRef, watchEffect} from 'vue'
+import {inject, onMounted, ref, toRef, watch} from 'vue'
 import {useVModel} from '@vueuse/core'
 import BCollapse from '../BCollapse.vue'
-import {accordionInjectionKey} from '../../utils'
-import {useBooleanish, useId} from '../../composables'
+// import  from '../BCollapse.vue'
+import {accordionInjectionKey, BvTriggerableEvent} from '../../utils'
+
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue:48]:
```suggestion
```

File: packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue [hunk 9]
```diff
@@ -29,41 +34,77 @@
...
+  (e: 'show', value: BvTriggerableEvent): void
+  (e: 'shown', value: BvTriggerableEvent): void
+  (e: 'hide', value: BvTriggerableEvent): void
+  (e: 'hidden', value: BvTriggerableEvent): void
+  (e: 'hide-prevented'): void
+  (e: 'show-prevented'): void
+  (e: 'update:modelValue', value: boolean): void
+}
+
+const emit = defineEmits<BAccordionItemEmits>()
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue:78]:
```suggestion
const emit = defineEmits<BAccordionItemEmits>()

```

File: packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue [hunk 10]
```diff
@@ -29,41 +34,77 @@
...
+  openItem: ref(''),
+  free: ref(false),
+})
+
+const computedId = useId(toRef(props, 'id'), 'accordion_item')
 
 onMounted(() => {
-  if (visibleBoolean.value) {
+  if (modelValue.value && !free.value) {
+    openItem.value = computedId.value
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue:99]: I am not certain, but I'm wondering if you can assign this in the provide default
```ts
const {openItem, free} = inject(accordionInjectionKey, {
  openItem: ref(computedId.value),
  free: ref(false),
})
```
There was that issue with some values not being in the correct state in between the finishing of mounting, and the finishing of the execution of the onMounted callback. I assume this would suffer from the same issue.

File: packages/bootstrap-vue-next/src/components/BCollapse.vue [hunk 11]
```diff
@@ -52,6 +41,15 @@ interface BCollapseEmits {
   (e: 'update:modelValue', value: boolean): void
 }
 
+const props = withDefaults(defineProps<BCollapseProps>(), {
+  modelValue: false,
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/components/BCollapse.vue:45]: Ensure you have fetched the main branch. There may be eslint rules that may be missing. (vue/require-default-prop)

File: packages/bootstrap-vue-next/src/utils/keys.ts [hunk 12]
```diff
@@ -45,7 +45,8 @@ export const avatarGroupInjectionKey: InjectionKey<{
 
 // BAccordion
 export const accordionInjectionKey: InjectionKey<{
-  id: Ref<string>
+  openItem: Ref<string>
```
Comment (VividLemon) [inline packages/bootstrap-vue-next/src/utils/keys.ts:48]: Wrap these in Readonly<> & use the equivalent runtime vue readonly() if needed

**Review by VividLemon — CHANGES_REQUESTED** [review]

File: packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue (hunk 10 above)
Comment (xvaara) [reply packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue:99]: The parent doesn't know what might be open, if accordionItem is opened with visible or toggle Booleanish. If multiple is open the "last one wins".

File: packages/bootstrap-vue-next/src/components/BAccordion/BAccordion.vue (hunk 6 above)
Comment (VividLemon) [reply packages/bootstrap-vue-next/src/components/BAccordion/BAccordion.vue:41]: You created a method to set this, but didn't wrap it in readonly
